--- #YAML:1.0
name:                       Labyrinth-Plugin-Articles-Newsletters
version:                    1.00
abstract:                   Newsletters plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  perl:                     5.006
  Encode:                   2.49
  Encode::MIME::Header:     2.13
  Labyrinth:                5.28
  Labyrinth::Plugin::Core:  5.18
  Session::Token:           1.008
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Labyrinth::Test::Harness: 1.05
  Test::More:               0.70

provides:
  Labyrinth::Plugin::Articles::Newsletters:
    file:     lib/Labyrinth/Plugin/Articles/Newsletters.pm
    version:  1.00

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  homepage:   http://labyrinth.missbarbell.co.uk
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Articles-Newsletters
  repository: http://github.com/barbie/labyrinth-plugin-articles-newsletters

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
